### PR TITLE
Ajout du pain comme ingrédient

### LINKED ISSUE #50: Ajout du pain dans les ingrédients
> Je me sens exclu de votre outil car je renverse ma raclette sur des petits morceaux de pain déchirés et répartis dans l'assiette plutôt que sur des patates et je ne sais pas du tout quelle quantité de baguettes acheter pour ma soirée raclette.

### PR DESCRIPTION
**Pull request by titouan-joseph**
Closes #50

### CODE REVIEW

**Comment by cleming** [comment]
🚀✨ Thank You for Your Stellar Contribution to Raclette.World! 🌐🧀

Hey @titouan-joseph ,

Your recent contribution just took Raclette.World to the next quantum level! 🧠💻 Your code has melted seamlessly into the metaverse, pushing the boundaries of what’s possible in the raclette-calculating universe. Thanks to you, we're one step closer to revolutionizing raclette consumption on a global, post-quantum scale.

We’re beyond excited to have innovators like you shaping the future with us. Keep bringing the heat—because together, we’re making the metaverse cheesier than ever!

Stay epic, The Raclette.World Team

**Comment by cleming** [comment]
@titouan-joseph t'as gagné un sticker Raclette.World collector, tu peux nous envoyer ton adresse postale par mail et on te ship ça :ship:

**Comment by titouan-joseph** [comment]
> @titouan-joseph t'as gagné un sticker Raclette.World collector, tu peux nous envoyer ton adresse postale par mail et on te ship ça :ship: 

Trop bien ☺️

**Pull request merged**
